using System;
using System.Collections.Generic;

namespace StarGen.Core.Epoch;

/// <summary>One calibration dial: dotted name, one-line doc, and live
/// accessors on a config. Ints round on set.</summary>
public sealed record KnobDef(
    string Name, string Doc,
    Func<EpochSimConfig, double> Get, Action<EpochSimConfig, double> Set);

/// <summary>The single index of every calibration knob — name-sorted, fully
/// documented, driving the artifact's KNOB lines, the REPL `knobs` command,
/// and docs/TUNING.md (which carries the consequence-of-turning prose).
/// A dial must never exist outside this table; KnobRegistryTests enforces
/// order, uniqueness, and accessor round-trips. Structural clock values
/// (Sim.YearsPerEpoch, Sim.EpochCount, MasterSeed) are identity, not
/// calibration — they live on the ESIM line.</summary>
public static class KnobRegistry
{
    private static KnobDef K(string name, string doc,
                             Func<EpochSimConfig, double> get,
                             Action<EpochSimConfig, double> set) =>
        new(name, doc, get, set);

    private static readonly KnobDef[] Table =
    {
        // ---- Character (mortality, succession, renown — slice G) ----
        K("Character.AssassinationBasePerYear",
          "ruler assassination hazard/year at full ambition, zero legitimacy",
          c => c.Character.AssassinationBasePerYear,
          (c, v) => c.Character.AssassinationBasePerYear = v),
        K("Character.CrisisLegitimacyHit",
          "legitimacy lost outright by an heirless succession",
          c => c.Character.CrisisLegitimacyHit,
          (c, v) => c.Character.CrisisLegitimacyHit = v),
        K("Character.DynastyPrestigePerReignYear",
          "dynastic prestige accrued per world-year of reign",
          c => c.Character.DynastyPrestigePerReignYear,
          (c, v) => c.Character.DynastyPrestigePerReignYear = v),
        K("Character.HeirMintAgeFraction",
          "heir mint age as a fraction of species lifespan",
          c => c.Character.HeirMintAgeFraction,
          (c, v) => c.Character.HeirMintAgeFraction = v),
        K("Character.MachineDeprecationPerYear",
          "flat deprecation hazard per world-year for machine minds",
          c => c.Character.MachineDeprecationPerYear,
          (c, v) => c.Character.MachineDeprecationPerYear = v),
        K("Character.MaxNotablesPerPolity",
          "living notables a polity carries at most (sparsity)",
          c => c.Character.MaxNotablesPerPolity,
          (c, v) => c.Character.MaxNotablesPerPolity = (int)Math.Round(v)),
        K("Character.MortalityShapePerYear",
          "death hazard per world-year at exactly one lifespan",
          c => c.Character.MortalityShapePerYear,
          (c, v) => c.Character.MortalityShapePerYear = v),
        K("Character.PrestigePerRenown",
          "ruler-prestige legitimacy gain per point of renown + prestige",
          c => c.Character.PrestigePerRenown,
          (c, v) => c.Character.PrestigePerRenown = v),
        K("Character.RenownAscension", "renown for taking a seat",
          c => c.Character.RenownAscension,
          (c, v) => c.Character.RenownAscension = v),
        K("Character.RenownNotable", "renown for being minted a notable",
          c => c.Character.RenownNotable,
          (c, v) => c.Character.RenownNotable = v),
        K("Character.RulerMintAgeFraction",
          "ruler/marshal/commander mint age as a lifespan fraction",
          c => c.Character.RulerMintAgeFraction,
          (c, v) => c.Character.RulerMintAgeFraction = v),

        // ---- Controller (genesis-AI standing-policy magnitudes) ----
        K("Controller.AlloysReservePerPort",
          "alloys banked per owned port (construction materials)",
          c => c.Controller.AlloysReservePerPort,
          (c, v) => c.Controller.AlloysReservePerPort = v),
        K("Controller.ArmamentsPerPortPerMilitancy",
          "armaments reserve per port per point of species militancy",
          c => c.Controller.ArmamentsPerPortPerMilitancy,
          (c, v) => c.Controller.ArmamentsPerPortPerMilitancy = v),
        K("Controller.BaseTariffRate",
          "tariff the AI levies on foreign goods at zero openness",
          c => c.Controller.BaseTariffRate,
          (c, v) => c.Controller.BaseTariffRate = v),
        K("Controller.CompositesReservePerPort",
          "composites banked per owned port",
          c => c.Controller.CompositesReservePerPort,
          (c, v) => c.Controller.CompositesReservePerPort = v),
        K("Controller.FuelReservePerPort",
          "fuel banked per owned port (navy fuel dumps, upkeep fallback)",
          c => c.Controller.FuelReservePerPort,
          (c, v) => c.Controller.FuelReservePerPort = v),
        K("Controller.MachineryReservePerPort",
          "machinery banked per owned port",
          c => c.Controller.MachineryReservePerPort,
          (c, v) => c.Controller.MachineryReservePerPort = v),
        K("Controller.MilitancyReserveGate",
          "militancy below which no armaments reserve is kept",
          c => c.Controller.MilitancyReserveGate,
          (c, v) => c.Controller.MilitancyReserveGate = v),
        K("Controller.NarcoticsProhibitBelowOpenness",
          "species openness below which narcotics are prohibited",
          c => c.Controller.NarcoticsProhibitBelowOpenness,
          (c, v) => c.Controller.NarcoticsProhibitBelowOpenness = v),
        K("Controller.NarcoticsRestrictBelowOpenness",
          "species openness below which narcotics are restricted",
          c => c.Controller.NarcoticsRestrictBelowOpenness,
          (c, v) => c.Controller.NarcoticsRestrictBelowOpenness = v),
        K("Controller.ProvisionsReservePerPort",
          "provisions reserve target per owned port (famine buffer)",
          c => c.Controller.ProvisionsReservePerPort,
          (c, v) => c.Controller.ProvisionsReservePerPort = v),
        K("Controller.RealmHungerGate",
          "no expeditions while realm mean subsistence is below this",
          c => c.Controller.RealmHungerGate,
          (c, v) => c.Controller.RealmHungerGate = v),
        K("Controller.ShipPartsReservePerPort",
          "ship components banked per owned port (fleet upkeep fallback)",
          c => c.Controller.ShipPartsReservePerPort,
          (c, v) => c.Controller.ShipPartsReservePerPort = v),

        // ---- Corporate (niches, charters, operations, deaths — slice G) ----
        K("Corporate.CartelSkim",
          "share of black-book value a cartel skims from buyers per epoch",
          c => c.Corporate.CartelSkim, (c, v) => c.Corporate.CartelSkim = v),
        K("Corporate.CartelValueFloor",
          "black-book value that reads as a profitable prohibited niche",
          c => c.Corporate.CartelValueFloor,
          (c, v) => c.Corporate.CartelValueFloor = v),
        K("Corporate.CharterCapitalFloor",
          "war-chest credits a merchant faction needs before chartering",
          c => c.Corporate.CharterCapitalFloor,
          (c, v) => c.Corporate.CharterCapitalFloor = v),
        K("Corporate.CharterOpennessGate",
          "host charter policy below which no charter is granted",
          c => c.Corporate.CharterOpennessGate,
          (c, v) => c.Corporate.CharterOpennessGate = v),
        K("Corporate.CharterPersistenceEpochs",
          "consecutive epochs a niche must persist before chartering",
          c => c.Corporate.CharterPersistenceEpochs,
          (c, v) => c.Corporate.CharterPersistenceEpochs = (int)Math.Round(v)),
        K("Corporate.DepositNichePotential",
          "extraction potential that reads as an unexploited deposit",
          c => c.Corporate.DepositNichePotential,
          (c, v) => c.Corporate.DepositNichePotential = v),
        K("Corporate.FabricationPriceRatio",
          "price-over-founding ratio that reads as an industrial gap",
          c => c.Corporate.FabricationPriceRatio,
          (c, v) => c.Corporate.FabricationPriceRatio = v),
        K("Corporate.FoundingGraceEpochs",
          "epochs after founding before the lean clock starts",
          c => c.Corporate.FoundingGraceEpochs,
          (c, v) => c.Corporate.FoundingGraceEpochs = (int)Math.Round(v)),
        K("Corporate.FreightNicheMargin",
          "relative lane price gradient that reads as a freight niche",
          c => c.Corporate.FreightNicheMargin,
          (c, v) => c.Corporate.FreightNicheMargin = v),
        K("Corporate.FreightPullComponents",
          "ship-components demand a freight line registers per epoch",
          c => c.Corporate.FreightPullComponents,
          (c, v) => c.Corporate.FreightPullComponents = v),
        K("Corporate.LeanReceiptsFloor",
          "epoch receipts below which a corporation counts as lean",
          c => c.Corporate.LeanReceiptsFloor,
          (c, v) => c.Corporate.LeanReceiptsFloor = v),
        K("Corporate.LobbyShare",
          "share of corporate credits lobbied to the aligned faction",
          c => c.Corporate.LobbyShare, (c, v) => c.Corporate.LobbyShare = v),
        K("Corporate.MagnateReceipts",
          "epoch receipts that mint the executive a magnate notable",
          c => c.Corporate.MagnateReceipts,
          (c, v) => c.Corporate.MagnateReceipts = v),
        K("Corporate.MaxFacilities", "facilities one corporation may hold",
          c => c.Corporate.MaxFacilities,
          (c, v) => c.Corporate.MaxFacilities = (int)Math.Round(v)),
        K("Corporate.NationalizeLegitimacyHit",
          "legitimacy a polity eats for nationalizing",
          c => c.Corporate.NationalizeLegitimacyHit,
          (c, v) => c.Corporate.NationalizeLegitimacyHit = v),
        K("Corporate.NationalizeWealthFactor",
          "corp credits over the host treasury that trigger nationalization",
          c => c.Corporate.NationalizeWealthFactor,
          (c, v) => c.Corporate.NationalizeWealthFactor = v),
        K("Corporate.NicheDeathEpochs",
          "consecutive lean epochs that kill the niche",
          c => c.Corporate.NicheDeathEpochs,
          (c, v) => c.Corporate.NicheDeathEpochs = (int)Math.Round(v)),
        K("Corporate.RaidCapacityFloor",
          "unescorted posted capacity that reads as a raiding niche",
          c => c.Corporate.RaidCapacityFloor,
          (c, v) => c.Corporate.RaidCapacityFloor = v),

        // ---- Economy (market engine, freight, credit, lifecycle) ----
        K("Economy.BasePriceCapital", "founding price of capital goods",
          c => c.Economy.BasePriceCapital, (c, v) => c.Economy.BasePriceCapital = v),
        K("Economy.BasePriceProcessed", "founding price of processed goods",
          c => c.Economy.BasePriceProcessed, (c, v) => c.Economy.BasePriceProcessed = v),
        K("Economy.BasePriceRaw", "founding price of raw goods",
          c => c.Economy.BasePriceRaw, (c, v) => c.Economy.BasePriceRaw = v),
        K("Economy.BlackMarketMarkup",
          "black-book margin multiple over the open price",
          c => c.Economy.BlackMarketMarkup, (c, v) => c.Economy.BlackMarketMarkup = v),
        K("Economy.ConditionDecayPerYear",
          "facility condition decay per year toward unmet upkeep",
          c => c.Economy.ConditionDecayPerYear,
          (c, v) => c.Economy.ConditionDecayPerYear = v),
        K("Economy.ConditionRecoveryPerYear",
          "facility condition recovery per year toward met upkeep",
          c => c.Economy.ConditionRecoveryPerYear,
          (c, v) => c.Economy.ConditionRecoveryPerYear = v),
        K("Economy.ElasticCeiling", "max demand multiple from cheap prices",
          c => c.Economy.ElasticCeiling, (c, v) => c.Economy.ElasticCeiling = v),
        K("Economy.ElasticFloor", "min demand multiple from dear prices",
          c => c.Economy.ElasticFloor, (c, v) => c.Economy.ElasticFloor = v),
        K("Economy.ExportShare",
          "share of a market's stock arbitrage/procurement may lift per step",
          c => c.Economy.ExportShare, (c, v) => c.Economy.ExportShare = v),
        K("Economy.FreightCostPerUnitPerHex", "freight fee per unit per hex",
          c => c.Economy.FreightCostPerUnitPerHex,
          (c, v) => c.Economy.FreightCostPerUnitPerHex = v),
        K("Economy.FuelPerUnitPerHex", "fuel drawn per unit shipped per hex",
          c => c.Economy.FuelPerUnitPerHex, (c, v) => c.Economy.FuelPerUnitPerHex = v),
        K("Economy.InitialCreditsPerPolity",
          "credits minted once per polity at entry (the mint)",
          c => c.Economy.InitialCreditsPerPolity,
          (c, v) => c.Economy.InitialCreditsPerPolity = v),
        K("Economy.InitialWealthPerPop",
          "household credits minted per pop at homeworld founding",
          c => c.Economy.InitialWealthPerPop,
          (c, v) => c.Economy.InitialWealthPerPop = v),
        K("Economy.LaborShare",
          "share of realized revenue paid to staffing segments as wages",
          c => c.Economy.LaborShare, (c, v) => c.Economy.LaborShare = v),
        K("Economy.LoanRatePerYear", "loan interest per world-year",
          c => c.Economy.LoanRatePerYear, (c, v) => c.Economy.LoanRatePerYear = v),
        K("Economy.LoanTermYears", "loan amortization term in world-years",
          c => c.Economy.LoanTermYears,
          (c, v) => c.Economy.LoanTermYears = (int)Math.Round(v)),
        K("Economy.LuxuryElasticity", "price response of luxury demand",
          c => c.Economy.LuxuryElasticity, (c, v) => c.Economy.LuxuryElasticity = v),
        K("Economy.LuxuryUnitsPerPopPerYear", "luxury units per pop per year",
          c => c.Economy.LuxuryUnitsPerPopPerYear,
          (c, v) => c.Economy.LuxuryUnitsPerPopPerYear = v),
        K("Economy.MaxPriceMultiple",
          "absolute price ceiling as a multiple of the founding price",
          c => c.Economy.MaxPriceMultiple, (c, v) => c.Economy.MaxPriceMultiple = v),
        K("Economy.MinUtilization",
          "production floor as prices crater (supply elasticity)",
          c => c.Economy.MinUtilization, (c, v) => c.Economy.MinUtilization = v),
        K("Economy.ParityHeadroom",
          "margin over arbitrage break-even in the import-parity price cap",
          c => c.Economy.ParityHeadroom, (c, v) => c.Economy.ParityHeadroom = v),
        K("Economy.PriceDriftExponent",
          "shape of price drift: (demand/supply)^exponent",
          c => c.Economy.PriceDriftExponent,
          (c, v) => c.Economy.PriceDriftExponent = v),
        K("Economy.PriceDriftMaxPerYear",
          "rate limit on price drift, fractional per world-year",
          c => c.Economy.PriceDriftMaxPerYear,
          (c, v) => c.Economy.PriceDriftMaxPerYear = v),
        K("Economy.PriceFloor", "absolute price floor",
          c => c.Economy.PriceFloor, (c, v) => c.Economy.PriceFloor = v),
        K("Economy.ReExportWeight",
          "strength of the re-export demand term (entrepôt formation)",
          c => c.Economy.ReExportWeight, (c, v) => c.Economy.ReExportWeight = v),
        K("Economy.ReserveReleaseTrigger",
          "subsistence fraction that opens polity provisions reserves",
          c => c.Economy.ReserveReleaseTrigger,
          (c, v) => c.Economy.ReserveReleaseTrigger = v),
        K("Economy.RestrictedFriction",
          "per-unit friction on restricted goods (share of dest price)",
          c => c.Economy.RestrictedFriction,
          (c, v) => c.Economy.RestrictedFriction = v),
        K("Economy.SoLElasticity", "price response of standard-of-living demand",
          c => c.Economy.SoLElasticity, (c, v) => c.Economy.SoLElasticity = v),
        K("Economy.SoLUnitsPerPopPerYear", "SoL units per pop per year",
          c => c.Economy.SoLUnitsPerPopPerYear,
          (c, v) => c.Economy.SoLUnitsPerPopPerYear = v),
        K("Economy.StockpileDecayPerYear",
          "durable reserve decay per year (perishables scale it in code)",
          c => c.Economy.StockpileDecayPerYear,
          (c, v) => c.Economy.StockpileDecayPerYear = v),
        K("Economy.SubsistenceElasticity", "price response of subsistence demand",
          c => c.Economy.SubsistenceElasticity,
          (c, v) => c.Economy.SubsistenceElasticity = v),
        K("Economy.SubsistenceUnitsPerPopPerYear",
          "subsistence units per pop per year (the famine dial)",
          c => c.Economy.SubsistenceUnitsPerPopPerYear,
          (c, v) => c.Economy.SubsistenceUnitsPerPopPerYear = v),
        K("Economy.WarWearinessPerYear", "war-weariness accrual per year (H)",
          c => c.Economy.WarWearinessPerYear,
          (c, v) => c.Economy.WarWearinessPerYear = v),

        // ---- Expansion (colonization and development spending) ----
        K("Expansion.ColonizationReachHexes", "off-lane colony reach in hexes",
          c => c.Expansion.ColonizationReachHexes,
          (c, v) => c.Expansion.ColonizationReachHexes = (int)Math.Round(v)),
        K("Expansion.ColonyCost",
          "expansion points per founding (recycled to the settlers)",
          c => c.Expansion.ColonyCost, (c, v) => c.Expansion.ColonyCost = v),
        K("Expansion.ColonySegmentSize", "founding colony population",
          c => c.Expansion.ColonySegmentSize,
          (c, v) => c.Expansion.ColonySegmentSize = v),
        K("Expansion.HomeworldSegmentSize", "homeworld founding population",
          c => c.Expansion.HomeworldSegmentSize,
          (c, v) => c.Expansion.HomeworldSegmentSize = v),
        K("Expansion.LaneCost", "development points per lane built",
          c => c.Expansion.LaneCost, (c, v) => c.Expansion.LaneCost = v),
        K("Expansion.PortUpgradeCostBase",
          "development points per tier raise, × current tier",
          c => c.Expansion.PortUpgradeCostBase,
          (c, v) => c.Expansion.PortUpgradeCostBase = v),
        K("Expansion.SegmentCapPerTier",
          "port population cap per port tier (shared across segments)",
          c => c.Expansion.SegmentCapPerTier,
          (c, v) => c.Expansion.SegmentCapPerTier = v),
        K("Expansion.SegmentGrowthPerYear",
          "logistic population growth per year toward the port cap",
          c => c.Expansion.SegmentGrowthPerYear,
          (c, v) => c.Expansion.SegmentGrowthPerYear = v),

        // ---- Faction (formation, pressure, appeasement, grievance — slice G) ----
        K("Faction.AppeasementDemandShare",
          "share of epoch receipts a full-strength faction demands",
          c => c.Faction.AppeasementDemandShare,
          (c, v) => c.Faction.AppeasementDemandShare = v),
        K("Faction.CoupIdeologyLurch",
          "official-line lurch toward the coup faction's target",
          c => c.Faction.CoupIdeologyLurch,
          (c, v) => c.Faction.CoupIdeologyLurch = v),
        K("Faction.CoupLegitimacyHit", "legitimacy lost by a successful coup",
          c => c.Faction.CoupLegitimacyHit,
          (c, v) => c.Faction.CoupLegitimacyHit = v),
        K("Faction.DissolveStrengthFloor",
          "strength below which a faction dissolves",
          c => c.Faction.DissolveStrengthFloor,
          (c, v) => c.Faction.DissolveStrengthFloor = v),
        K("Faction.FormMinShare",
          "population share an interest needs to coalesce",
          c => c.Faction.FormMinShare, (c, v) => c.Faction.FormMinShare = v),
        K("Faction.FrontierDistanceFraction",
          "port distance (fraction of reach) past which a domain is frontier",
          c => c.Faction.FrontierDistanceFraction,
          (c, v) => c.Faction.FrontierDistanceFraction = v),
        K("Faction.GraduationGripFactor",
          "grip multiplier on legitimacy x enforcement in the graduation test",
          c => c.Faction.GraduationGripFactor,
          (c, v) => c.Faction.GraduationGripFactor = v),
        K("Faction.GrievanceDecayPerYear",
          "grievance decay per world-year when fully appeased",
          c => c.Faction.GrievanceDecayPerYear,
          (c, v) => c.Faction.GrievanceDecayPerYear = v),
        K("Faction.GrievancePerYear",
          "grievance accrual per world-year of unappeased strength",
          c => c.Faction.GrievancePerYear,
          (c, v) => c.Faction.GrievancePerYear = v),
        K("Faction.IdeologyGapToForm",
          "mean axis distance from the official line that reads as dissent",
          c => c.Faction.IdeologyGapToForm,
          (c, v) => c.Faction.IdeologyGapToForm = v),
        K("Faction.MaxBudgetPressure",
          "cap on one faction's per-epoch budget/ideology bend",
          c => c.Faction.MaxBudgetPressure,
          (c, v) => c.Faction.MaxBudgetPressure = v),
        K("Faction.MilitaryRenownToForm",
          "officer renown x militancy needed for a military faction",
          c => c.Faction.MilitaryRenownToForm,
          (c, v) => c.Faction.MilitaryRenownToForm = v),
        K("Faction.PatronRenownWeight",
          "faction-strength weight of a patron's renown",
          c => c.Faction.PatronRenownWeight,
          (c, v) => c.Faction.PatronRenownWeight = v),
        K("Faction.PressureRatePerYear",
          "budget/ideology drift toward agendas per world-year",
          c => c.Faction.PressureRatePerYear,
          (c, v) => c.Faction.PressureRatePerYear = v),
        K("Faction.RevoltGrievanceKeep",
          "fraction of grievance a crushed revolt keeps (repression compounds)",
          c => c.Faction.RevoltGrievanceKeep,
          (c, v) => c.Faction.RevoltGrievanceKeep = v),
        K("Faction.RevoltLegitimacyHit", "legitimacy lost crushing a revolt",
          c => c.Faction.RevoltLegitimacyHit,
          (c, v) => c.Faction.RevoltLegitimacyHit = v),
        K("Faction.SacralAxisLine",
          "sacral-axis position below which segments read as faithful",
          c => c.Faction.SacralAxisLine,
          (c, v) => c.Faction.SacralAxisLine = v),
        K("Faction.WealthStrengthWeight",
          "faction-strength weight of its wealth share",
          c => c.Faction.WealthStrengthWeight,
          (c, v) => c.Faction.WealthStrengthWeight = v),

        // ---- Fleet (yards, posted freight, supply, attrition, lineages) ----
        K("Fleet.AttritionHullLossPerYear",
          "hull fraction wrecked per year while readiness is below the floor",
          c => c.Fleet.AttritionHullLossPerYear,
          (c, v) => c.Fleet.AttritionHullLossPerYear = v),
        K("Fleet.AttritionReadinessFloor",
          "readiness below which unsupplied fleets start losing hulls",
          c => c.Fleet.AttritionReadinessFloor,
          (c, v) => c.Fleet.AttritionReadinessFloor = v),
        K("Fleet.EnduranceHexesPerPoint",
          "off-lane hexes reachable per point of OffLaneEndurance",
          c => c.Fleet.EnduranceHexesPerPoint,
          (c, v) => c.Fleet.EnduranceHexesPerPoint = v),
        K("Fleet.FreightTripsPerYearBase",
          "posted round trips per year at speed 1 over one hex",
          c => c.Fleet.FreightTripsPerYearBase,
          (c, v) => c.Fleet.FreightTripsPerYearBase = v),
        K("Fleet.FuelPerHullPerHexMoved",
          "fuel units per hull per hex of expedition movement",
          c => c.Fleet.FuelPerHullPerHexMoved,
          (c, v) => c.Fleet.FuelPerHullPerHexMoved = v),
        K("Fleet.HullArmamentsBase",
          "armaments per Medium warship hull at the yard (× size cost factor)",
          c => c.Fleet.HullArmamentsBase, (c, v) => c.Fleet.HullArmamentsBase = v),
        K("Fleet.HullComponentsBase",
          "ship components per Medium hull at the yard (× size cost factor)",
          c => c.Fleet.HullComponentsBase, (c, v) => c.Fleet.HullComponentsBase = v),
        K("Fleet.MarkGradeStep",
          "component-grade gain over a design that mints its next mark",
          c => c.Fleet.MarkGradeStep, (c, v) => c.Fleet.MarkGradeStep = v),
        K("Fleet.MilitaryPullComponents",
          "ship-components demand a funded polity posts at its yard port",
          c => c.Fleet.MilitaryPullComponents,
          (c, v) => c.Fleet.MilitaryPullComponents = v),
        K("Fleet.ReadinessDecayPerYear",
          "readiness decay per year toward the unmet supply fraction",
          c => c.Fleet.ReadinessDecayPerYear,
          (c, v) => c.Fleet.ReadinessDecayPerYear = v),
        K("Fleet.ReadinessRecoveryPerYear",
          "readiness recovery per year toward the met supply fraction",
          c => c.Fleet.ReadinessRecoveryPerYear,
          (c, v) => c.Fleet.ReadinessRecoveryPerYear = v),
        K("Fleet.ReserveUpkeepFactor",
          "upkeep multiplier for docked Reserve-posture fleets",
          c => c.Fleet.ReserveUpkeepFactor,
          (c, v) => c.Fleet.ReserveUpkeepFactor = v),
        K("Fleet.StarterColonyHulls",
          "colony hulls in the homeworld starter fleet",
          c => c.Fleet.StarterColonyHulls,
          (c, v) => c.Fleet.StarterColonyHulls = (int)Math.Round(v)),
        K("Fleet.StarterEscortPerMilitancy",
          "starter escort hulls per point of species militancy",
          c => c.Fleet.StarterEscortPerMilitancy,
          (c, v) => c.Fleet.StarterEscortPerMilitancy = v),
        K("Fleet.StarterFreightHulls",
          "freight hulls in the homeworld starter fleet",
          c => c.Fleet.StarterFreightHulls,
          (c, v) => c.Fleet.StarterFreightHulls = (int)Math.Round(v)),
        K("Fleet.UpkeepFuelShare",
          "share of fleet upkeep drawn as fuel (rest armaments/components)",
          c => c.Fleet.UpkeepFuelShare, (c, v) => c.Fleet.UpkeepFuelShare = v),
        K("Fleet.UpkeepUnitsPerPointPerYear",
          "goods units per point of fleet Upkeep vector per year",
          c => c.Fleet.UpkeepUnitsPerPointPerYear,
          (c, v) => c.Fleet.UpkeepUnitsPerPointPerYear = v),
        K("Fleet.YardHullsPerTierPerYear",
          "hulls a yard lays down per yard tier per year",
          c => c.Fleet.YardHullsPerTierPerYear,
          (c, v) => c.Fleet.YardHullsPerTierPerYear = v),

        // ---- Genesis (emergence windows; natives — slice H) ----
        K("Genesis.EmergenceWindowYears",
          "latest world-year a polity may enter (staggered emergence)",
          c => c.Genesis.EmergenceWindowYears,
          (c, v) => c.Genesis.EmergenceWindowYears = (int)Math.Round(v)),
        K("Genesis.NativePopulationSize",
          "population an emerging native people starts with",
          c => c.Genesis.NativePopulationSize,
          (c, v) => c.Genesis.NativePopulationSize = v),
        K("Genesis.NativeWindowYears",
          "world-year the last native emergence date projects onto",
          c => c.Genesis.NativeWindowYears,
          (c, v) => c.Genesis.NativeWindowYears = (int)Math.Round(v)),
        K("Genesis.ProtectorateDelayEpochs",
          "epochs a protectorate policy delays a native emergence",
          c => c.Genesis.ProtectorateDelayEpochs,
          (c, v) => c.Genesis.ProtectorateDelayEpochs = (int)Math.Round(v)),
        K("Genesis.UpliftAccelerationEpochs",
          "epochs an uplift host (Life ≥ 2) advances a native emergence",
          c => c.Genesis.UpliftAccelerationEpochs,
          (c, v) => c.Genesis.UpliftAccelerationEpochs = (int)Math.Round(v)),

        // ---- Infrastructure (port physics and construction) ----
        K("Infrastructure.ConstructionDevGate",
          "development treasury below which the construction pull is quiet",
          c => c.Infrastructure.ConstructionDevGate,
          (c, v) => c.Infrastructure.ConstructionDevGate = v),
        K("Infrastructure.ConstructionPullAlloys",
          "alloys demand per under-capacity port per epoch",
          c => c.Infrastructure.ConstructionPullAlloys,
          (c, v) => c.Infrastructure.ConstructionPullAlloys = v),
        K("Infrastructure.ConstructionPullComposites",
          "composites demand per under-capacity port per epoch",
          c => c.Infrastructure.ConstructionPullComposites,
          (c, v) => c.Infrastructure.ConstructionPullComposites = v),
        K("Infrastructure.ConstructionPullMachinery",
          "machinery demand per under-capacity port per epoch",
          c => c.Infrastructure.ConstructionPullMachinery,
          (c, v) => c.Infrastructure.ConstructionPullMachinery = v),
        K("Infrastructure.ConstructionScoreFloor",
          "minimum siting × price score before anything gets built",
          c => c.Infrastructure.ConstructionScoreFloor,
          (c, v) => c.Infrastructure.ConstructionScoreFloor = v),
        K("Infrastructure.FacilitiesPerPortTier",
          "facility cap per port tier (the construction ceiling)",
          c => c.Infrastructure.FacilitiesPerPortTier,
          (c, v) => c.Infrastructure.FacilitiesPerPortTier = (int)Math.Round(v)),
        K("Infrastructure.FoodSecurityPremium",
          "how decisively extraction must beat farmland at colony founding",
          c => c.Infrastructure.FoodSecurityPremium,
          (c, v) => c.Infrastructure.FoodSecurityPremium = v),
        K("Infrastructure.HomeworldPortTier", "homeworld founding port tier",
          c => c.Infrastructure.HomeworldPortTier,
          (c, v) => c.Infrastructure.HomeworldPortTier = (int)Math.Round(v)),
        K("Infrastructure.InterPortRangeBaseHexes", "tier-1 lane reach in hexes",
          c => c.Infrastructure.InterPortRangeBaseHexes,
          (c, v) => c.Infrastructure.InterPortRangeBaseHexes = (int)Math.Round(v)),
        K("Infrastructure.InterPortRangePerTierHexes", "extra lane reach per tier",
          c => c.Infrastructure.InterPortRangePerTierHexes,
          (c, v) => c.Infrastructure.InterPortRangePerTierHexes = (int)Math.Round(v)),
        K("Infrastructure.MaxPortTier", "highest port tier",
          c => c.Infrastructure.MaxPortTier,
          (c, v) => c.Infrastructure.MaxPortTier = (int)Math.Round(v)),
        K("Infrastructure.ServiceRadiusBaseHexes", "tier-1 service radius in hexes",
          c => c.Infrastructure.ServiceRadiusBaseHexes,
          (c, v) => c.Infrastructure.ServiceRadiusBaseHexes = (int)Math.Round(v)),
        K("Infrastructure.ServiceRadiusPerTierHexes", "extra service radius per tier",
          c => c.Infrastructure.ServiceRadiusPerTierHexes,
          (c, v) => c.Infrastructure.ServiceRadiusPerTierHexes = (int)Math.Round(v)),

        // ---- Interior (legitimacy, cohesion, enforcement — slice G) ----
        K("Interior.EnforcementBase",
          "enforcement floor (a state with no navy still polices)",
          c => c.Interior.EnforcementBase,
          (c, v) => c.Interior.EnforcementBase = v),
        K("Interior.EnforcementPerWarshipPerPort",
          "enforcement per warship hull per owned port",
          c => c.Interior.EnforcementPerWarshipPerPort,
          (c, v) => c.Interior.EnforcementPerWarshipPerPort = v),
        K("Interior.LegitimacyAccommodationWeight",
          "base weight of the cultural-accommodation legitimacy term",
          c => c.Interior.LegitimacyAccommodationWeight,
          (c, v) => c.Interior.LegitimacyAccommodationWeight = v),
        K("Interior.LegitimacyIdeologyWeight",
          "base weight of the official-vs-popular alignment legitimacy term",
          c => c.Interior.LegitimacyIdeologyWeight,
          (c, v) => c.Interior.LegitimacyIdeologyWeight = v),
        K("Interior.LegitimacyProsperityWeight",
          "base weight of the prosperity legitimacy term",
          c => c.Interior.LegitimacyProsperityWeight,
          (c, v) => c.Interior.LegitimacyProsperityWeight = v),
        K("Interior.LegitimacyRulerWeight",
          "base weight of the ruler-prestige legitimacy term",
          c => c.Interior.LegitimacyRulerWeight,
          (c, v) => c.Interior.LegitimacyRulerWeight = v),
        K("Interior.LegitimacyWarWeight",
          "base weight of the war-outcome legitimacy term (neutral until H)",
          c => c.Interior.LegitimacyWarWeight,
          (c, v) => c.Interior.LegitimacyWarWeight = v),
        K("Interior.OfficialDriftPerYear",
          "official-ideology drift toward the popular line at zero inertia",
          c => c.Interior.OfficialDriftPerYear,
          (c, v) => c.Interior.OfficialDriftPerYear = v),
        K("Interior.SoLTrendGain",
          "how strongly the SoL trend moves prosperity legitimacy",
          c => c.Interior.SoLTrendGain,
          (c, v) => c.Interior.SoLTrendGain = v),
        K("Interior.StrainDistanceWeight",
          "cohesion strain at mean port distance = colonization reach",
          c => c.Interior.StrainDistanceWeight,
          (c, v) => c.Interior.StrainDistanceWeight = v),
        K("Interior.StrainPerCulture",
          "cohesion strain per culture beyond the founding one",
          c => c.Interior.StrainPerCulture,
          (c, v) => c.Interior.StrainPerCulture = v),
        K("Interior.StrainPerPort",
          "cohesion strain per owned port beyond the first",
          c => c.Interior.StrainPerPort,
          (c, v) => c.Interior.StrainPerPort = v),

        // ---- Population (demographics, migration, ideology) ----
        K("Population.FamineLine",
          "subsistence fraction below which segments shrink and famines chronicle",
          c => c.Population.FamineLine, (c, v) => c.Population.FamineLine = v),
        K("Population.FamineShrinkPerYear",
          "segment shrink per year of unmet subsistence",
          c => c.Population.FamineShrinkPerYear,
          (c, v) => c.Population.FamineShrinkPerYear = v),
        K("Population.HungerIdeologyLine",
          "subsistence below which ideology turns Authority/Sacral",
          c => c.Population.HungerIdeologyLine,
          (c, v) => c.Population.HungerIdeologyLine = v),
        K("Population.IdeologyDriftPerYear",
          "ideology drift toward lived conditions per year",
          c => c.Population.IdeologyDriftPerYear,
          (c, v) => c.Population.IdeologyDriftPerYear = v),
        K("Population.MigrationMinGradient",
          "minimum attractiveness gradient before anyone packs",
          c => c.Population.MigrationMinGradient,
          (c, v) => c.Population.MigrationMinGradient = v),
        K("Population.MigrationRatePerYear",
          "fraction of a segment migrating per year at full pull",
          c => c.Population.MigrationRatePerYear,
          (c, v) => c.Population.MigrationRatePerYear = v),
        K("Population.ProsperityIdeologyLine",
          "SoL above which ideology turns Individual/Open",
          c => c.Population.ProsperityIdeologyLine,
          (c, v) => c.Population.ProsperityIdeologyLine = v),
        K("Population.RefugeeLine",
          "subsistence fraction below which migration turns refugee",
          c => c.Population.RefugeeLine, (c, v) => c.Population.RefugeeLine = v),
        K("Population.RefugeeMultiplier",
          "refugee flight speed as a multiple of base migration",
          c => c.Population.RefugeeMultiplier,
          (c, v) => c.Population.RefugeeMultiplier = v),
        K("Population.SoLDriftPerYear",
          "SoL movement toward the cleared fraction per year",
          c => c.Population.SoLDriftPerYear,
          (c, v) => c.Population.SoLDriftPerYear = v),

        // ---- Relations (contact, warmth/tension sources — slice H) ----
        K("Relations.AgitationTensionWeight",
          "tension weight of the loudest military faction on either side",
          c => c.Relations.AgitationTensionWeight,
          (c, v) => c.Relations.AgitationTensionWeight = v),
        K("Relations.BreakWarmthPenalty",
          "warmth lost outright when a treaty rung is broken",
          c => c.Relations.BreakWarmthPenalty,
          (c, v) => c.Relations.BreakWarmthPenalty = v),
        K("Relations.ClaimTensionWeight",
          "tension per live standing claim (saturating at 1)",
          c => c.Relations.ClaimTensionWeight,
          (c, v) => c.Relations.ClaimTensionWeight = v),
        K("Relations.ContactReachHexes",
          "nearest cross-owner port distance at which polities meet",
          c => c.Relations.ContactReachHexes,
          (c, v) => c.Relations.ContactReachHexes = (int)Math.Round(v)),
        K("Relations.DynasticTieLapseYears",
          "years before a tie lapses into its succession claim",
          c => c.Relations.DynasticTieLapseYears,
          (c, v) => c.Relations.DynasticTieLapseYears = (int)Math.Round(v)),
        K("Relations.DynasticTieWarmth",
          "warmth per live dynastic instrument (counted up to three)",
          c => c.Relations.DynasticTieWarmth,
          (c, v) => c.Relations.DynasticTieWarmth = v),
        K("Relations.FederationAllianceEpochs",
          "epochs a defense alliance must stand before fusion can fire",
          c => c.Relations.FederationAllianceEpochs,
          (c, v) => c.Relations.FederationAllianceEpochs = (int)Math.Round(v)),
        K("Relations.FederationCohesionFloor",
          "both cohesions needed to fuse (troubled realms fracture instead)",
          c => c.Relations.FederationCohesionFloor,
          (c, v) => c.Relations.FederationCohesionFloor = v),
        K("Relations.FederationIdeologyGapMax",
          "official-ideology gap above which the merge is off",
          c => c.Relations.FederationIdeologyGapMax,
          (c, v) => c.Relations.FederationIdeologyGapMax = v),
        K("Relations.FederationOpennessFloor",
          "composed openness both sides need to contemplate fusion",
          c => c.Relations.FederationOpennessFloor,
          (c, v) => c.Relations.FederationOpennessFloor = v),
        K("Relations.IdeologyGapCooling",
          "warmth cut per point of official-ideology gap",
          c => c.Relations.IdeologyGapCooling,
          (c, v) => c.Relations.IdeologyGapCooling = v),
        K("Relations.IdeologyTensionWeight",
          "tension weight of ideology gap × mean ruler zeal",
          c => c.Relations.IdeologyTensionWeight,
          (c, v) => c.Relations.IdeologyTensionWeight = v),
        K("Relations.InterdictionTensionWeight",
          "tension weight while either blockades the other's ports",
          c => c.Relations.InterdictionTensionWeight,
          (c, v) => c.Relations.InterdictionTensionWeight = v),
        K("Relations.KinClaimSegmentFloor",
          "kin population under the other's rule that raises a claim",
          c => c.Relations.KinClaimSegmentFloor,
          (c, v) => c.Relations.KinClaimSegmentFloor = v),
        K("Relations.MilitancyTensionWeight",
          "tension weight of the pair's mean composed militancy",
          c => c.Relations.MilitancyTensionWeight,
          (c, v) => c.Relations.MilitancyTensionWeight = v),
        K("Relations.NonAggressionDamping",
          "tension-target damping under a non-aggression rung or above",
          c => c.Relations.NonAggressionDamping,
          (c, v) => c.Relations.NonAggressionDamping = v),
        K("Relations.OverlapSaturation",
          "overlapping cross-owner port pairs at full overlap tension",
          c => c.Relations.OverlapSaturation,
          (c, v) => c.Relations.OverlapSaturation = v),
        K("Relations.OverlapTensionWeight",
          "tension weight of saturated service-area overlap",
          c => c.Relations.OverlapTensionWeight,
          (c, v) => c.Relations.OverlapTensionWeight = v),
        K("Relations.PactTariffFactor",
          "tariff multiplier between trade-pact partners (the cut)",
          c => c.Relations.PactTariffFactor,
          (c, v) => c.Relations.PactTariffFactor = v),
        K("Relations.StrangenessWeight",
          "warmth-baseline cut per point of openness-filtered strangeness",
          c => c.Relations.StrangenessWeight,
          (c, v) => c.Relations.StrangenessWeight = v),
        K("Relations.TensionRelaxPerYear",
          "tension relaxation per year once sources resolve",
          c => c.Relations.TensionRelaxPerYear,
          (c, v) => c.Relations.TensionRelaxPerYear = v),
        K("Relations.TensionRisePerYear",
          "tension rise per year toward a loaded target",
          c => c.Relations.TensionRisePerYear,
          (c, v) => c.Relations.TensionRisePerYear = v),
        K("Relations.TradeSaturation",
          "posted cross-border capacity at full trade warmth",
          c => c.Relations.TradeSaturation,
          (c, v) => c.Relations.TradeSaturation = v),
        K("Relations.TradeWarmthWeight",
          "warmth weight of saturated cross-border trade",
          c => c.Relations.TradeWarmthWeight,
          (c, v) => c.Relations.TradeWarmthWeight = v),
        K("Relations.TreatyGateBase",
          "warmth required to offer or accept the first rung",
          c => c.Relations.TreatyGateBase,
          (c, v) => c.Relations.TreatyGateBase = v),
        K("Relations.TreatyGateStep",
          "additional warmth gate per rung above the first",
          c => c.Relations.TreatyGateStep,
          (c, v) => c.Relations.TreatyGateStep = v),
        K("Relations.TreatyWarmthWeight",
          "warmth weight of the treaty ladder at its top rung",
          c => c.Relations.TreatyWarmthWeight,
          (c, v) => c.Relations.TreatyWarmthWeight = v),
        K("Relations.VassalAbsorptionEpochs",
          "epochs of stable vassalage before peaceful annexation can fire",
          c => c.Relations.VassalAbsorptionEpochs,
          (c, v) => c.Relations.VassalAbsorptionEpochs = (int)Math.Round(v)),
        K("Relations.VassalAbsorptionWarmth",
          "warmth at which long vassalage completes as annexation",
          c => c.Relations.VassalAbsorptionWarmth,
          (c, v) => c.Relations.VassalAbsorptionWarmth = v),
        K("Relations.VassalSecessionCohesion",
          "overlord cohesion below which vassals bid for independence",
          c => c.Relations.VassalSecessionCohesion,
          (c, v) => c.Relations.VassalSecessionCohesion = v),
        K("Relations.VassalStrengthRatio",
          "vassal/overlord strength ratio at which chosen vassalage binds",
          c => c.Relations.VassalStrengthRatio,
          (c, v) => c.Relations.VassalStrengthRatio = v),
        K("Relations.VassalTributeShare",
          "income share a vassal ships up each epoch",
          c => c.Relations.VassalTributeShare,
          (c, v) => c.Relations.VassalTributeShare = v),
        K("Relations.WarmthDriftPerYear",
          "warmth drift toward its source target per year",
          c => c.Relations.WarmthDriftPerYear,
          (c, v) => c.Relations.WarmthDriftPerYear = v),

        // ---- Tech (ladder costs, research, diffusion — slice G) ----
        // (War family sorts after Tech — see the end of the table)
        K("Tech.AstroRadiusPerTierHexes",
          "extra port service radius per Astrogation tier above standard",
          c => c.Tech.AstroRadiusPerTierHexes,
          (c, v) => c.Tech.AstroRadiusPerTierHexes = (int)Math.Round(v)),
        K("Tech.AstroRangePerTierHexes",
          "extra inter-port lane reach per Astrogation tier above standard",
          c => c.Tech.AstroRangePerTierHexes,
          (c, v) => c.Tech.AstroRangePerTierHexes = (int)Math.Round(v)),
        K("Tech.BaseThreshold", "progress points to leave tier 1",
          c => c.Tech.BaseThreshold, (c, v) => c.Tech.BaseThreshold = v),
        K("Tech.ComputeBoost",
          "research effectiveness multiplier at compute parity",
          c => c.Tech.ComputeBoost, (c, v) => c.Tech.ComputeBoost = v),
        K("Tech.LifeGrowthPerTier",
          "population growth multiplier per Life tier above standard",
          c => c.Tech.LifeGrowthPerTier,
          (c, v) => c.Tech.LifeGrowthPerTier = v),
        K("Tech.ProgressPerExotic",
          "research progress per Refined Exotics unit consumed",
          c => c.Tech.ProgressPerExotic,
          (c, v) => c.Tech.ProgressPerExotic = v),
        K("Tech.ResearchPullCompute",
          "compute demand a funded research line registers per epoch",
          c => c.Tech.ResearchPullCompute,
          (c, v) => c.Tech.ResearchPullCompute = v),
        K("Tech.ResearchPullExotics",
          "refined-exotics demand a funded research line registers per epoch",
          c => c.Tech.ResearchPullExotics,
          (c, v) => c.Tech.ResearchPullExotics = v),
        K("Tech.SalvagePerHullPerYear",
          "military progress per out-graded wrecked hull in reach per year",
          c => c.Tech.SalvagePerHullPerYear,
          (c, v) => c.Tech.SalvagePerHullPerYear = v),
        K("Tech.ThresholdGrowth", "geometric ladder cost growth per tier",
          c => c.Tech.ThresholdGrowth, (c, v) => c.Tech.ThresholdGrowth = v),
        K("Tech.TradeDiffusionPerYear",
          "progress per year of full-volume open trade with a leader",
          c => c.Tech.TradeDiffusionPerYear,
          (c, v) => c.Tech.TradeDiffusionPerYear = v),
        K("Tech.TradeVolumeSaturation",
          "posted lane capacity at which trade diffusion saturates",
          c => c.Tech.TradeVolumeSaturation,
          (c, v) => c.Tech.TradeVolumeSaturation = v),

        // ---- War (spark, appetite, causes, conduct — slice H) ----
        K("War.AllySupportFactor",
          "engagement weight of a coalition partner's distant navy",
          c => c.War.AllySupportFactor,
          (c, v) => c.War.AllySupportFactor = v),
        K("War.AttackStrengthRatio",
          "own strength per defender-coalition strength needed to declare",
          c => c.War.AttackStrengthRatio,
          (c, v) => c.War.AttackStrengthRatio = v),
        K("War.BattleFacilityDamage",
          "facility condition lost under a decisive attacker victory",
          c => c.War.BattleFacilityDamage,
          (c, v) => c.War.BattleFacilityDamage = v),
        K("War.BlockadeHoldEpochs",
          "epochs a lane stays cut before the objective counts taken",
          c => c.War.BlockadeHoldEpochs,
          (c, v) => c.War.BlockadeHoldEpochs = (int)Math.Round(v)),
        K("War.CommanderDeathOnRout",
          "chance the beaten commander dies with a decisive day",
          c => c.War.CommanderDeathOnRout,
          (c, v) => c.War.CommanderDeathOnRout = v),
        K("War.CrusadeThreshold",
          "ideology gap × ruler zeal that arms the crusade cause",
          c => c.War.CrusadeThreshold,
          (c, v) => c.War.CrusadeThreshold = v),
        K("War.DefeatLegitimacy",
          "legitimacy a settlement costs the loser's throne",
          c => c.War.DefeatLegitimacy, (c, v) => c.War.DefeatLegitimacy = v),
        K("War.ExhaustionPerLoss",
          "exhaustion per fully-wrecked own warship roster",
          c => c.War.ExhaustionPerLoss,
          (c, v) => c.War.ExhaustionPerLoss = v),
        K("War.FleetDestroyedShare",
          "defender strength share below which its navy counts broken",
          c => c.War.FleetDestroyedShare,
          (c, v) => c.War.FleetDestroyedShare = v),
        K("War.FleetExhaustionShare",
          "strength share of the mustered coalition at which a side breaks",
          c => c.War.FleetExhaustionShare,
          (c, v) => c.War.FleetExhaustionShare = v),
        K("War.FortressDefensePerTier",
          "fractional defender-power bonus per fortress tier",
          c => c.War.FortressDefensePerTier,
          (c, v) => c.War.FortressDefensePerTier = v),
        K("War.GrievanceDischargeFloor",
          "military-faction strength × grievance that arms discharge",
          c => c.War.GrievanceDischargeFloor,
          (c, v) => c.War.GrievanceDischargeFloor = v),
        K("War.IncidentRatePerEpoch",
          "border-incident probability per epoch at full overlap",
          c => c.War.IncidentRatePerEpoch,
          (c, v) => c.War.IncidentRatePerEpoch = v),
        K("War.IncidentTensionBump",
          "instant tension bump per border incident",
          c => c.War.IncidentTensionBump,
          (c, v) => c.War.IncidentTensionBump = v),
        K("War.LegitimacyCollapseFloor",
          "legitimacy below which a belligerent's politics count broken",
          c => c.War.LegitimacyCollapseFloor,
          (c, v) => c.War.LegitimacyCollapseFloor = v),
        K("War.LossAttrition",
          "hull-share both sides wreck in an attrition round",
          c => c.War.LossAttrition, (c, v) => c.War.LossAttrition = v),
        K("War.LossDecisiveLoser",
          "hull-share the loser of a decisive engagement wrecks",
          c => c.War.LossDecisiveLoser,
          (c, v) => c.War.LossDecisiveLoser = v),
        K("War.LossDecisiveWinner",
          "hull-share the winner of a decisive engagement wrecks",
          c => c.War.LossDecisiveWinner,
          (c, v) => c.War.LossDecisiveWinner = v),
        K("War.LossStalemate",
          "hull-share both sides wreck in a stalemate",
          c => c.War.LossStalemate, (c, v) => c.War.LossStalemate = v),
        K("War.MobileResponseShare",
          "defender away-station share that answers (and bleeds) at a front",
          c => c.War.MobileResponseShare,
          (c, v) => c.War.MobileResponseShare = v),
        K("War.PriceShockMultiple",
          "own price over founding that arms resource seizure",
          c => c.War.PriceShockMultiple,
          (c, v) => c.War.PriceShockMultiple = v),
        K("War.RenownPerVictory",
          "renown a decisive victory mints its commander",
          c => c.War.RenownPerVictory,
          (c, v) => c.War.RenownPerVictory = v),
        K("War.ReparationsShare",
          "share of the loser's treasury a reparations settlement moves",
          c => c.War.ReparationsShare,
          (c, v) => c.War.ReparationsShare = v),
        K("War.SettlementTensionRelief",
          "fractional tension unloaded by a settlement",
          c => c.War.SettlementTensionRelief,
          (c, v) => c.War.SettlementTensionRelief = v),
        K("War.SiegeBaseEpochs",
          "siege epochs before any larder or fortress extends it",
          c => c.War.SiegeBaseEpochs,
          (c, v) => c.War.SiegeBaseEpochs = (int)Math.Round(v)),
        K("War.SiegeProvisionEpochsCap",
          "cap on siege epochs a full larder can add",
          c => c.War.SiegeProvisionEpochsCap,
          (c, v) => c.War.SiegeProvisionEpochsCap = v),
        K("War.SupplyPenaltyPerHex",
          "attacker power lost per hex from its supply base (floor 0.5)",
          c => c.War.SupplyPenaltyPerHex,
          (c, v) => c.War.SupplyPenaltyPerHex = v),
        K("War.VeteranMilitancyBump",
          "militancy a war's end adds to both sides' military factions",
          c => c.War.VeteranMilitancyBump,
          (c, v) => c.War.VeteranMilitancyBump = v),
        K("War.VictoryLegitimacy",
          "legitimacy a settlement hands the winner's throne",
          c => c.War.VictoryLegitimacy,
          (c, v) => c.War.VictoryLegitimacy = v),
        K("War.WarAppetiteThreshold",
          "tension × (0.5 + militancy) needed to declare",
          c => c.War.WarAppetiteThreshold,
          (c, v) => c.War.WarAppetiteThreshold = v),
        K("War.WarHeroRenown",
          "renown at which a victorious commander is hailed a war hero",
          c => c.War.WarHeroRenown, (c, v) => c.War.WarHeroRenown = v),
        K("War.WarTensionFloor",
          "tension below which incidents fizzle instead of escalating",
          c => c.War.WarTensionFloor,
          (c, v) => c.War.WarTensionFloor = v),
    };

    private static readonly Dictionary<string, KnobDef> ByName = Build();

    private static Dictionary<string, KnobDef> Build()
    {
        var map = new Dictionary<string, KnobDef>(Table.Length);
        foreach (var k in Table) map.Add(k.Name, k);
        return map;
    }

    /// <summary>Every knob, name-sorted (the table is maintained sorted;
    /// tests enforce it).</summary>
    public static IReadOnlyList<KnobDef> All => Table;

    public static KnobDef? Find(string name) =>
        ByName.TryGetValue(name, out var knob) ? knob : null;
}
