using System;
using System.Collections.Generic;

namespace StarGen.Core.Epoch;

/// <summary>One calibration dial: dotted name, one-line doc, and live
/// accessors on a config. Ints round on set.</summary>
public sealed record KnobDef(
    string Name, string Doc,
    Func<EpochSimConfig, double> Get, Action<EpochSimConfig, double> Set);

/// <summary>The single index of every calibration knob — name-sorted, fully
/// documented, driving the artifact's KNOB lines, the REPL `knobs` command,
/// and docs/TUNING.md (which carries the consequence-of-turning prose).
/// A dial must never exist outside this table; KnobRegistryTests enforces
/// order, uniqueness, and accessor round-trips. Structural clock values
/// (Sim.YearsPerEpoch, Sim.EpochCount, MasterSeed) are identity, not
/// calibration — they live on the ESIM line.</summary>
public static class KnobRegistry
{
    private static KnobDef K(string name, string doc,
                             Func<EpochSimConfig, double> get,
                             Action<EpochSimConfig, double> set) =>
        new(name, doc, get, set);

    private static readonly KnobDef[] Table =
    {
        // ---- Controller (genesis-AI standing-policy magnitudes) ----
        K("Controller.AlloysReservePerPort",
          "alloys banked per owned port (construction materials)",
          c => c.Controller.AlloysReservePerPort,
          (c, v) => c.Controller.AlloysReservePerPort = v),
        K("Controller.ArmamentsPerPortPerMilitancy",
          "armaments reserve per port per point of species militancy",
          c => c.Controller.ArmamentsPerPortPerMilitancy,
          (c, v) => c.Controller.ArmamentsPerPortPerMilitancy = v),
        K("Controller.CompositesReservePerPort",
          "composites banked per owned port",
          c => c.Controller.CompositesReservePerPort,
          (c, v) => c.Controller.CompositesReservePerPort = v),
        K("Controller.MachineryReservePerPort",
          "machinery banked per owned port",
          c => c.Controller.MachineryReservePerPort,
          (c, v) => c.Controller.MachineryReservePerPort = v),
        K("Controller.MilitancyReserveGate",
          "militancy below which no armaments reserve is kept",
          c => c.Controller.MilitancyReserveGate,
          (c, v) => c.Controller.MilitancyReserveGate = v),
        K("Controller.NarcoticsProhibitBelowOpenness",
          "species openness below which narcotics are prohibited",
          c => c.Controller.NarcoticsProhibitBelowOpenness,
          (c, v) => c.Controller.NarcoticsProhibitBelowOpenness = v),
        K("Controller.NarcoticsRestrictBelowOpenness",
          "species openness below which narcotics are restricted",
          c => c.Controller.NarcoticsRestrictBelowOpenness,
          (c, v) => c.Controller.NarcoticsRestrictBelowOpenness = v),
        K("Controller.ProvisionsReservePerPort",
          "provisions reserve target per owned port (famine buffer)",
          c => c.Controller.ProvisionsReservePerPort,
          (c, v) => c.Controller.ProvisionsReservePerPort = v),
        K("Controller.RealmHungerGate",
          "no expeditions while realm mean subsistence is below this",
          c => c.Controller.RealmHungerGate,
          (c, v) => c.Controller.RealmHungerGate = v),

        // ---- Economy (market engine, freight, credit, lifecycle) ----
        K("Economy.BasePriceCapital", "founding price of capital goods",
          c => c.Economy.BasePriceCapital, (c, v) => c.Economy.BasePriceCapital = v),
        K("Economy.BasePriceProcessed", "founding price of processed goods",
          c => c.Economy.BasePriceProcessed, (c, v) => c.Economy.BasePriceProcessed = v),
        K("Economy.BasePriceRaw", "founding price of raw goods",
          c => c.Economy.BasePriceRaw, (c, v) => c.Economy.BasePriceRaw = v),
        K("Economy.BlackMarketMarkup",
          "black-book margin multiple over the open price",
          c => c.Economy.BlackMarketMarkup, (c, v) => c.Economy.BlackMarketMarkup = v),
        K("Economy.ConditionDecayPerYear",
          "facility condition decay per year toward unmet upkeep",
          c => c.Economy.ConditionDecayPerYear,
          (c, v) => c.Economy.ConditionDecayPerYear = v),
        K("Economy.ConditionRecoveryPerYear",
          "facility condition recovery per year toward met upkeep",
          c => c.Economy.ConditionRecoveryPerYear,
          (c, v) => c.Economy.ConditionRecoveryPerYear = v),
        K("Economy.ElasticCeiling", "max demand multiple from cheap prices",
          c => c.Economy.ElasticCeiling, (c, v) => c.Economy.ElasticCeiling = v),
        K("Economy.ElasticFloor", "min demand multiple from dear prices",
          c => c.Economy.ElasticFloor, (c, v) => c.Economy.ElasticFloor = v),
        K("Economy.ExportShare",
          "share of a market's stock arbitrage/procurement may lift per step",
          c => c.Economy.ExportShare, (c, v) => c.Economy.ExportShare = v),
        K("Economy.FreightCostPerUnitPerHex", "freight fee per unit per hex",
          c => c.Economy.FreightCostPerUnitPerHex,
          (c, v) => c.Economy.FreightCostPerUnitPerHex = v),
        K("Economy.FuelPerUnitPerHex", "fuel drawn per unit shipped per hex",
          c => c.Economy.FuelPerUnitPerHex, (c, v) => c.Economy.FuelPerUnitPerHex = v),
        K("Economy.InitialCreditsPerPolity",
          "credits minted once per polity at entry (the mint)",
          c => c.Economy.InitialCreditsPerPolity,
          (c, v) => c.Economy.InitialCreditsPerPolity = v),
        K("Economy.InitialWealthPerPop",
          "household credits minted per pop at homeworld founding",
          c => c.Economy.InitialWealthPerPop,
          (c, v) => c.Economy.InitialWealthPerPop = v),
        K("Economy.LaborShare",
          "share of realized revenue paid to staffing segments as wages",
          c => c.Economy.LaborShare, (c, v) => c.Economy.LaborShare = v),
        K("Economy.LoanRatePerYear", "loan interest per world-year",
          c => c.Economy.LoanRatePerYear, (c, v) => c.Economy.LoanRatePerYear = v),
        K("Economy.LoanTermYears", "loan amortization term in world-years",
          c => c.Economy.LoanTermYears,
          (c, v) => c.Economy.LoanTermYears = (int)Math.Round(v)),
        K("Economy.LuxuryElasticity", "price response of luxury demand",
          c => c.Economy.LuxuryElasticity, (c, v) => c.Economy.LuxuryElasticity = v),
        K("Economy.LuxuryUnitsPerPopPerYear", "luxury units per pop per year",
          c => c.Economy.LuxuryUnitsPerPopPerYear,
          (c, v) => c.Economy.LuxuryUnitsPerPopPerYear = v),
        K("Economy.MaxPriceMultiple",
          "absolute price ceiling as a multiple of the founding price",
          c => c.Economy.MaxPriceMultiple, (c, v) => c.Economy.MaxPriceMultiple = v),
        K("Economy.MinUtilization",
          "production floor as prices crater (supply elasticity)",
          c => c.Economy.MinUtilization, (c, v) => c.Economy.MinUtilization = v),
        K("Economy.ParityHeadroom",
          "margin over arbitrage break-even in the import-parity price cap",
          c => c.Economy.ParityHeadroom, (c, v) => c.Economy.ParityHeadroom = v),
        K("Economy.PriceDriftExponent",
          "shape of price drift: (demand/supply)^exponent",
          c => c.Economy.PriceDriftExponent,
          (c, v) => c.Economy.PriceDriftExponent = v),
        K("Economy.PriceDriftMaxPerYear",
          "rate limit on price drift, fractional per world-year",
          c => c.Economy.PriceDriftMaxPerYear,
          (c, v) => c.Economy.PriceDriftMaxPerYear = v),
        K("Economy.PriceFloor", "absolute price floor",
          c => c.Economy.PriceFloor, (c, v) => c.Economy.PriceFloor = v),
        K("Economy.ReExportWeight",
          "strength of the re-export demand term (entrepôt formation)",
          c => c.Economy.ReExportWeight, (c, v) => c.Economy.ReExportWeight = v),
        K("Economy.ReserveReleaseTrigger",
          "subsistence fraction that opens polity provisions reserves",
          c => c.Economy.ReserveReleaseTrigger,
          (c, v) => c.Economy.ReserveReleaseTrigger = v),
        K("Economy.RestrictedFriction",
          "per-unit friction on restricted goods (share of dest price)",
          c => c.Economy.RestrictedFriction,
          (c, v) => c.Economy.RestrictedFriction = v),
        K("Economy.SoLElasticity", "price response of standard-of-living demand",
          c => c.Economy.SoLElasticity, (c, v) => c.Economy.SoLElasticity = v),
        K("Economy.SoLUnitsPerPopPerYear", "SoL units per pop per year",
          c => c.Economy.SoLUnitsPerPopPerYear,
          (c, v) => c.Economy.SoLUnitsPerPopPerYear = v),
        K("Economy.StockpileDecayPerYear",
          "durable reserve decay per year (perishables scale it in code)",
          c => c.Economy.StockpileDecayPerYear,
          (c, v) => c.Economy.StockpileDecayPerYear = v),
        K("Economy.SubsistenceElasticity", "price response of subsistence demand",
          c => c.Economy.SubsistenceElasticity,
          (c, v) => c.Economy.SubsistenceElasticity = v),
        K("Economy.SubsistenceUnitsPerPopPerYear",
          "subsistence units per pop per year (the famine dial)",
          c => c.Economy.SubsistenceUnitsPerPopPerYear,
          (c, v) => c.Economy.SubsistenceUnitsPerPopPerYear = v),
        K("Economy.TechTierStub", "config-level producer tech tier until slice G",
          c => c.Economy.TechTierStub,
          (c, v) => c.Economy.TechTierStub = (int)Math.Round(v)),
        K("Economy.WarWearinessPerYear", "war-weariness accrual per year (H)",
          c => c.Economy.WarWearinessPerYear,
          (c, v) => c.Economy.WarWearinessPerYear = v),

        // ---- Expansion (colonization and development spending) ----
        K("Expansion.ColonizationReachHexes", "off-lane colony reach in hexes",
          c => c.Expansion.ColonizationReachHexes,
          (c, v) => c.Expansion.ColonizationReachHexes = (int)Math.Round(v)),
        K("Expansion.ColonyCost",
          "expansion points per founding (recycled to the settlers)",
          c => c.Expansion.ColonyCost, (c, v) => c.Expansion.ColonyCost = v),
        K("Expansion.ColonySegmentSize", "founding colony population",
          c => c.Expansion.ColonySegmentSize,
          (c, v) => c.Expansion.ColonySegmentSize = v),
        K("Expansion.HomeworldSegmentSize", "homeworld founding population",
          c => c.Expansion.HomeworldSegmentSize,
          (c, v) => c.Expansion.HomeworldSegmentSize = v),
        K("Expansion.LaneCost", "development points per lane built",
          c => c.Expansion.LaneCost, (c, v) => c.Expansion.LaneCost = v),
        K("Expansion.PortUpgradeCostBase",
          "development points per tier raise, × current tier",
          c => c.Expansion.PortUpgradeCostBase,
          (c, v) => c.Expansion.PortUpgradeCostBase = v),
        K("Expansion.SegmentCapPerTier",
          "port population cap per port tier (shared across segments)",
          c => c.Expansion.SegmentCapPerTier,
          (c, v) => c.Expansion.SegmentCapPerTier = v),
        K("Expansion.SegmentGrowthPerYear",
          "logistic population growth per year toward the port cap",
          c => c.Expansion.SegmentGrowthPerYear,
          (c, v) => c.Expansion.SegmentGrowthPerYear = v),

        // ---- Genesis (stub until slice F) ----
        K("Genesis.EmergenceWindowYears",
          "latest world-year a polity may enter (staggered emergence)",
          c => c.Genesis.EmergenceWindowYears,
          (c, v) => c.Genesis.EmergenceWindowYears = (int)Math.Round(v)),

        // ---- Infrastructure (port physics and construction) ----
        K("Infrastructure.ConstructionDevGate",
          "development treasury below which the construction pull is quiet",
          c => c.Infrastructure.ConstructionDevGate,
          (c, v) => c.Infrastructure.ConstructionDevGate = v),
        K("Infrastructure.ConstructionPullAlloys",
          "alloys demand per under-capacity port per epoch",
          c => c.Infrastructure.ConstructionPullAlloys,
          (c, v) => c.Infrastructure.ConstructionPullAlloys = v),
        K("Infrastructure.ConstructionPullComposites",
          "composites demand per under-capacity port per epoch",
          c => c.Infrastructure.ConstructionPullComposites,
          (c, v) => c.Infrastructure.ConstructionPullComposites = v),
        K("Infrastructure.ConstructionPullMachinery",
          "machinery demand per under-capacity port per epoch",
          c => c.Infrastructure.ConstructionPullMachinery,
          (c, v) => c.Infrastructure.ConstructionPullMachinery = v),
        K("Infrastructure.ConstructionScoreFloor",
          "minimum siting × price score before anything gets built",
          c => c.Infrastructure.ConstructionScoreFloor,
          (c, v) => c.Infrastructure.ConstructionScoreFloor = v),
        K("Infrastructure.FacilitiesPerPortTier",
          "facility cap per port tier (the construction ceiling)",
          c => c.Infrastructure.FacilitiesPerPortTier,
          (c, v) => c.Infrastructure.FacilitiesPerPortTier = (int)Math.Round(v)),
        K("Infrastructure.FoodSecurityPremium",
          "how decisively extraction must beat farmland at colony founding",
          c => c.Infrastructure.FoodSecurityPremium,
          (c, v) => c.Infrastructure.FoodSecurityPremium = v),
        K("Infrastructure.HomeworldPortTier", "homeworld founding port tier",
          c => c.Infrastructure.HomeworldPortTier,
          (c, v) => c.Infrastructure.HomeworldPortTier = (int)Math.Round(v)),
        K("Infrastructure.InterPortRangeBaseHexes", "tier-1 lane reach in hexes",
          c => c.Infrastructure.InterPortRangeBaseHexes,
          (c, v) => c.Infrastructure.InterPortRangeBaseHexes = (int)Math.Round(v)),
        K("Infrastructure.InterPortRangePerTierHexes", "extra lane reach per tier",
          c => c.Infrastructure.InterPortRangePerTierHexes,
          (c, v) => c.Infrastructure.InterPortRangePerTierHexes = (int)Math.Round(v)),
        K("Infrastructure.MaxPortTier", "highest port tier",
          c => c.Infrastructure.MaxPortTier,
          (c, v) => c.Infrastructure.MaxPortTier = (int)Math.Round(v)),
        K("Infrastructure.ServiceRadiusBaseHexes", "tier-1 service radius in hexes",
          c => c.Infrastructure.ServiceRadiusBaseHexes,
          (c, v) => c.Infrastructure.ServiceRadiusBaseHexes = (int)Math.Round(v)),
        K("Infrastructure.ServiceRadiusPerTierHexes", "extra service radius per tier",
          c => c.Infrastructure.ServiceRadiusPerTierHexes,
          (c, v) => c.Infrastructure.ServiceRadiusPerTierHexes = (int)Math.Round(v)),

        // ---- Population (demographics, migration, ideology) ----
        K("Population.FamineLine",
          "subsistence fraction below which segments shrink and famines chronicle",
          c => c.Population.FamineLine, (c, v) => c.Population.FamineLine = v),
        K("Population.FamineShrinkPerYear",
          "segment shrink per year of unmet subsistence",
          c => c.Population.FamineShrinkPerYear,
          (c, v) => c.Population.FamineShrinkPerYear = v),
        K("Population.HungerIdeologyLine",
          "subsistence below which ideology turns Authority/Sacral",
          c => c.Population.HungerIdeologyLine,
          (c, v) => c.Population.HungerIdeologyLine = v),
        K("Population.IdeologyDriftPerYear",
          "ideology drift toward lived conditions per year",
          c => c.Population.IdeologyDriftPerYear,
          (c, v) => c.Population.IdeologyDriftPerYear = v),
        K("Population.MigrationMinGradient",
          "minimum attractiveness gradient before anyone packs",
          c => c.Population.MigrationMinGradient,
          (c, v) => c.Population.MigrationMinGradient = v),
        K("Population.MigrationRatePerYear",
          "fraction of a segment migrating per year at full pull",
          c => c.Population.MigrationRatePerYear,
          (c, v) => c.Population.MigrationRatePerYear = v),
        K("Population.ProsperityIdeologyLine",
          "SoL above which ideology turns Individual/Open",
          c => c.Population.ProsperityIdeologyLine,
          (c, v) => c.Population.ProsperityIdeologyLine = v),
        K("Population.RefugeeLine",
          "subsistence fraction below which migration turns refugee",
          c => c.Population.RefugeeLine, (c, v) => c.Population.RefugeeLine = v),
        K("Population.RefugeeMultiplier",
          "refugee flight speed as a multiple of base migration",
          c => c.Population.RefugeeMultiplier,
          (c, v) => c.Population.RefugeeMultiplier = v),
        K("Population.SoLDriftPerYear",
          "SoL movement toward the cleared fraction per year",
          c => c.Population.SoLDriftPerYear,
          (c, v) => c.Population.SoLDriftPerYear = v),
    };

    private static readonly Dictionary<string, KnobDef> ByName = Build();

    private static Dictionary<string, KnobDef> Build()
    {
        var map = new Dictionary<string, KnobDef>(Table.Length);
        foreach (var k in Table) map.Add(k.Name, k);
        return map;
    }

    /// <summary>Every knob, name-sorted (the table is maintained sorted;
    /// tests enforce it).</summary>
    public static IReadOnlyList<KnobDef> All => Table;

    public static KnobDef? Find(string name) =>
        ByName.TryGetValue(name, out var knob) ? knob : null;
}
